"""nuts-rs-wasm's demo MMM under nutpie and under tapewasm in V8.

    uv run --python 3.12 --no-project --with pymc-marketing --with nutpie --with -e . \\
      python bench/mmm.py native /path/to/nuts-rs-wasm
    node bench/mmm.mjs
    python bench/mmm.py table

The model is nuts-rs-wasm's `examples/mmm/model.py` on its CSV, unchanged, sampled as
its tapewasm backend PR was: 2 chains of 750 warmup and 500 draws, target_accept 0.9.
"""
import json, os, platform, runpy, sys, time

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "models", "mmm")
FITS, TUNE, DRAWS, CHAINS = 10, 750, 500, 2
FREE = ["adstock_alpha", "saturation_lam", "saturation_beta", "gamma_fourier", "gamma_control",
        "intercept_contribution", "y_sigma"]


def min_bulk_ess(draws):  # (chain, draw, param); rank-based, so either space scores the same
    from arviz_stats.base import array_stats
    return float(np.min(array_stats.ess(np.asarray(draws), chain_axis=0, draw_axis=1, method="bulk")))


def native(nrw):
    import nutpie, pymc, pymc_marketing
    from pymcwasm.build import build

    ns = runpy.run_path(os.path.join(nrw, "examples/mmm/model.py"),
                        init_globals={"DATA_PATH": os.path.join(nrw, "examples/mmm/mmm_example.csv")})
    model = ns["model"]
    for reroll in ("auto", "never"):
        build(model, os.path.join(OUT, reroll), log_lik=False, expand=False, reroll=reroll)
    compiled = nutpie.compile_pymc_model(model)
    fits = []
    for s in range(FITS):
        t = time.perf_counter()
        idata = nutpie.sample(compiled, draws=DRAWS, tune=TUNE, chains=CHAINS, cores=1, seed=s + 1,
                              target_accept=0.9, save_warmup=True, progress_bar=False)
        secs = time.perf_counter() - t
        post = np.concatenate([np.asarray(idata.posterior[v]).reshape(CHAINS, DRAWS, -1) for v in FREE], 2)
        fits.append({"seconds": secs, "evals": int(idata.warmup_sample_stats["n_steps"].sum()
                                                   + idata.sample_stats["n_steps"].sum()),
                     "step_size": float(idata.sample_stats["step_size"].mean()),
                     "divergences": int(idata.sample_stats["diverging"].sum()),
                     "min_ess": min_bulk_ess(post)})
    versions = {"python": platform.python_version(), "machine": platform.machine(), "pymc": pymc.__version__,
                "pymc-marketing": pymc_marketing.__version__, "nutpie": nutpie.__version__}
    json.dump({"versions": versions, "fits": fits}, open(os.path.join(OUT, "nutpie.json"), "w"))


def table():
    import statistics as st

    nat = json.load(open(os.path.join(OUT, "nutpie.json")))
    tw = json.load(open(os.path.join(OUT, "tapewasm.json")))
    rows = [("CPython · nutpie", nat["fits"])]
    for run in tw["runs"]:
        for f in run["fits"]:
            f["min_ess"] = min_bulk_ess(np.asarray(f.pop("draws")).reshape(CHAINS, DRAWS, tw["nParams"]))
        rows.append((f"V8 · tapewasm · reroll {run['reroll']} · grad-based metric "
                     f"{'on' if run['gradBased'] else 'off'}", run["fits"]))
    med = lambda fits, f: st.median(f(x) for x in fits)
    lines = ["# nuts-rs-wasm's demo MMM", "", "Generated by `bench/mmm.py table`; see its docstring.", "",
             f"- CPython: {nat['versions']}", f"- V8: {tw['versions']}", "",
             f"Median of {FITS} fits of {CHAINS} chains × ({TUNE} warmup + {DRAWS} draws), target_accept 0.9.",
             "", "| sampler | sample s | gradient evals | step size | min bulk ESS | ESS/s | µs per eval | divergences |",
             "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"]
    for name, fits in rows:
        lines.append(
            f"| {name} | {med(fits, lambda x: x['seconds']):.2f} | {med(fits, lambda x: x['evals']):,.0f} "
            f"| {med(fits, lambda x: x['step_size']):.3f} | {med(fits, lambda x: x['min_ess']):.0f} "
            f"| {med(fits, lambda x: x['min_ess'] / x['seconds']):.1f} "
            f"| {med(fits, lambda x: x['seconds'] / x['evals'] * 1e6):.1f} | {sum(x['divergences'] for x in fits)} |")
    open(os.path.join(HERE, "RESULTS-mmm.md"), "w").write("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    native(sys.argv[2]) if sys.argv[1] == "native" else table()
