"""bench/results-*.json into bench/RESULTS.md.

The last column is how far a sampler's means sit from nutpie's, in nutpie's posterior sd,
worst over the model's scalars: the check that a faster row drew the same posterior.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
# Below this many effective draws a mean is not yet the posterior's, for any sampler.
CONVERGED_ESS = 100
LABEL = {
    ("pyodide", "py"): "Pyodide · PyMC NUTS · Python linker",
    ("pyodide", "wasm"): "Pyodide · PyMC NUTS · `mode=\"WASM\"`",
    ("pyodide", "pymcwasm"): "Pyodide · `pymcwasm.sample`",
    ("cpython", "pymc"): "CPython · PyMC NUTS",
    ("cpython", "nutpie"): "CPython · nutpie",
}


def load(name):
    with open(os.path.join(HERE, f"results-{name}.json")) as f:
        return json.load(f)


def overview(rows, models):
    """ESS per second for every model and sampler, on one page."""
    keys = list(LABEL)
    lines = ["## Overview: min bulk ESS per second of sampling", "",
             "| model | parameters | " + " | ".join(LABEL[k] for k in keys) + " |",
             "| --- | ---: |" + " ---: |" * len(keys)]
    for model in models:
        mine = {(r["env"], r["sampler"]): r for r in rows if r["model"] == model}
        ref = mine.get(("cpython", "nutpie"), {})
        cells = []
        for k in keys:
            r = mine.get(k)
            if r is None or "error" in r:
                cells.append("error" if r else "")
            elif "skipped" in r:
                cells.append("skipped")
            else:
                cells.append(f"{r['ess_per_s']:.1f}" + (" †" if r["min_ess"] < CONVERGED_ESS else ""))
        lines.append(f"| {model} | {len(ref.get('means', [])) or '?'} | " + " | ".join(cells) + " |")
    return lines + ["", f"† fewer than {CONVERGED_ESS} effective draws: that row's posterior is not "
                        "settled at this length, so neither is its distance from nutpie's.", ""]


def main():
    native, browser = load("native"), load("browser")
    rows = native["rows"] + browser["rows"]
    models = json.load(open(os.path.join(HERE, "models", "index.json")))
    out = ["# Benchmark results", "",
           "Generated by `bench/table.py`; see `bench/README.md` for what is run and how.", "",
           f"- CPython: {native['versions']}", f"- Pyodide: {browser['versions']}", ""]
    out += overview(rows, models)
    for model in models:
        mine = [r for r in rows if r["model"] == model]
        ref = next((r for r in mine if r["sampler"] == "nutpie" and "means" in r), None)
        n = len(ref["means"]) if ref else "?"
        out += [f"## {model} ({n} parameters)", "",
                "| | compile s | sample s | min ESS | ESS/s | means vs nutpie |",
                "| --- | ---: | ---: | ---: | ---: | ---: |"]
        for env, sampler in LABEL:
            r = next((r for r in mine if (r["env"], r["sampler"]) == (env, sampler)), None)
            if r is None:
                continue
            if "error" in r or "skipped" in r:
                out.append(f"| {LABEL[env, sampler]} | | | | | {r.get('skipped') or r['error']} |")
                continue
            drift = ""
            if ref and len(r["means"]) == len(ref["means"]):
                drift = f"{max(abs(a - b) / max(s, 1e-12) for a, b, s in zip(r['means'], ref['means'], ref['sds'])):.2f} sd"
            mark = " †" if r["min_ess"] < CONVERGED_ESS else ""
            out.append(f"| {LABEL[env, sampler]} | {r['compile_s']:.2f} | {r['sample_s']:.2f} | "
                       f"{r['min_ess']:.0f}{mark} | {r['ess_per_s']:.1f} | {drift} |")
        out.append("")
    with open(os.path.join(HERE, "RESULTS.md"), "w") as f:
        f.write("\n".join(out))
    print("\n".join(out))


if __name__ == "__main__":
    main()
